"""Small, secret-free models used by the Psiphon session manager."""
from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any


DISABLED = "DISABLED"
STOPPED = "STOPPED"
STARTING = "STARTING"
CONNECTING = "CONNECTING"
CONNECTED = "CONNECTED"
HEALTHY = "HEALTHY"
ROTATING = "ROTATING"
RECONNECTING = "RECONNECTING"
DEGRADED = "DEGRADED"
FAILED = "FAILED"

PUBLIC_STATES = frozenset(
    {
        DISABLED,
        STOPPED,
        STARTING,
        CONNECTING,
        CONNECTED,
        HEALTHY,
        ROTATING,
        RECONNECTING,
        DEGRADED,
        FAILED,
    }
)


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


def utc_now_iso() -> str:
    return utc_now().isoformat()


def bounded_float(value: object, default: float = 0.0, high: float = 86_400_000.0) -> float:
    try:
        parsed = float(value)
    except (TypeError, ValueError):
        return default
    if parsed < 0:
        return default
    return min(parsed, high)


def safe_region(value: object) -> str:
    """Keep a Core notice useful without echoing arbitrary notice data."""
    text = str(value or "").upper().strip()
    if len(text) == 2 and text.isalpha():
        return text
    return ""


@dataclass(frozen=True)
class ManagedUpstream:
    """A transient catalog record; URL is never persisted or returned by APIs."""

    proxy_id: str
    url: str


@dataclass(frozen=True)
class PsiphonBackendLease:
    """One in-flight VLESS session attached to the active Core generation."""

    lease_id: str
    generation: int
    host: str
    port: int


@dataclass(frozen=True)
class TunnelHealth:
    tcp_ok: bool
    latency_ms: float = 0.0
    exit_ip: str = ""
    exit_country: str = ""
    exit_region: str = ""
    reason: str = ""


@dataclass
class SessionStatus:
    """Operational state. Values here are intentionally safe for the dashboard."""

    enabled: bool
    core_available: bool = False
    state: str = DISABLED
    session_id: str = ""
    session_started_at: str = ""
    session_expires_at: str = ""
    selected_location: str = ""
    tunnel_setup_ms: float = 0.0
    exit_ip: str = ""
    exit_country: str = ""
    exit_region: str = ""
    tcp_tunnel_health: str = "UNKNOWN"
    # This integration deliberately uses the official Core port-forward mode,
    # not a TUN/packet-tunnel endpoint. Railway public ingress is not UDP.
    udp_tunnel_health: str = "NOT_SUPPORTED"
    last_rotation_at: str = ""
    rotation_count: int = 0
    last_proxy_retest_at: str = ""
    last_successful_health_check_at: str = ""
    last_error: str = ""
    restart_count: int = 0
    last_exit_code: int | None = None
    active_psiphon_ws_sessions: int = 0

    def public(self, now: datetime | None = None) -> dict[str, Any]:
        now = now or utc_now()
        started = _parse_time(self.session_started_at)
        expires = _parse_time(self.session_expires_at)
        age = max(0, int((now - started).total_seconds())) if started else 0
        remaining = max(0, int((expires - now).total_seconds())) if expires else 0
        return {
            "enabled": self.enabled,
            "core_available": self.core_available,
            "available": self.state == HEALTHY,
            "psiphon_ws_status": (
                "AVAILABLE" if self.state == HEALTHY else "UNAVAILABLE"
            ),
            "state": self.state if self.state in PUBLIC_STATES else FAILED,
            "selected_location": self.selected_location or "UNAVAILABLE",
            "tunnel_setup_ms": round(bounded_float(self.tunnel_setup_ms), 2) or None,
            "session_started_at": self.session_started_at or None,
            "session_expires_at": self.session_expires_at or None,
            "next_rotation_at": self.session_expires_at or None,
            "session_age_seconds": age if started else None,
            "remaining_lifetime_seconds": remaining if expires else None,
            "last_rotation_at": self.last_rotation_at or None,
            "rotation_count": max(0, int(self.rotation_count or 0)),
            "last_proxy_retest_at": self.last_proxy_retest_at or None,
            "last_successful_health_check_at": (
                self.last_successful_health_check_at or None
            ),
            "tcp_tunnel_health": self.tcp_tunnel_health,
            "udp_tunnel_health": self.udp_tunnel_health,
            "exit_ip": self.exit_ip or None,
            "exit_country": self.exit_country or None,
            "exit_region": self.exit_region or None,
            # Error reasons are a small allow-list generated by the manager;
            # raw Core notices, config values, paths, and process output never
            # cross this boundary.
            "last_error": self.last_error or None,
            "restart_count": max(0, int(self.restart_count or 0)),
            "active_psiphon_ws_sessions": max(
                0, int(self.active_psiphon_ws_sessions or 0),
            ),
        }


def _parse_time(value: str) -> datetime | None:
    try:
        parsed = datetime.fromisoformat(value)
    except (TypeError, ValueError):
        return None
    if parsed.tzinfo is None:
        return None
    return parsed.astimezone(timezone.utc)